config/routes.rb
Rails.application.routes.draw do

  get 'sites/jak_prispet'
  get 'sites/o_nas'
  get 'sites/kontakty'
  devise_for :users
  resources :events
  resources :posts
  resources :users
  resources :sponsors
  resources :photos

  get 'home/index'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  enum event_type: [:planned, :hobby_group, :course, :festival]

  alias_attribute :type, :event_type

  validates :title, presence: true, length: { minimum: 3 }
  validates :event_type, presence: true
  validate :date_around_today

  TYPE_TITLES = {
    planned: 'Plánované akce',
    hobby_group: 'Kroužky',
    course: 'Kurzy',
    festival: 'Festival na konci léta'
  }.freeze

  def event_type_title
    TYPE_TITLES[event_type.to_sym]
  end

  def date_around_today
    if !date
      errors.add(:date, 'is required')
    elsif date <= 10.year.ago || date >= 2.years.from_now
      errors.add(:date, 'can not be more than 1 year in the past or 2 years in the future')
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :name, :image, presence: true
  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :text, presence: true

  belongs_to :user
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  validates :name, presence: true
  validates :web, format: URI.regexp(%w(http https))
  mount_uploader :logo, LogoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, :password, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    check_params!
    @events = Event.all
    @events = @events.where(type: params[:type]) if params[:type]
    @events = @events.order(date: :desc)
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Akce byla vytvořena.'
    else
      render action: 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event, notice: 'Akce byla aktualizována.'
    else
      render action: 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :type)
  end

  def check_params!
    return unless params[:type]
    raise ArgumentError unless Event.event_types.keys.include?(params[:type])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.create(photo_params)

    if @photo.save
      redirect_to @photo, notice: 'Fotka byla přidána.'
    else
      render action: 'new'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to photos_path
  end

  private

  def photo_params
    params.require(:photo).permit(:name, :image, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.persisted?
      redirect_to @post, notice: 'Článek byl vytvořen.'
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: 'Článek byl aktualizován.'
    else
      render action: 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def o_nas
  end

  def jak_prispet
  end

  def kontakty
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def index
    @sponsors = Sponsor.all
  end

  def new
    @sponsor = Sponsor.new
  end

  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  def show
    @sponsor = Sponsor.find(params[:id])
  end

  def create
    @sponsor = Sponsor.create(sponsor_params)

    if @sponsor.save
      redirect_to @sponsor, notice: 'Sponzor byl vytvořen.'
    else
      render action: 'new'
    end
  end

  def update
    @sponsor = Sponsor.find(params[:id])

    if @sponsor.update(sponsor_params)
      redirect_to @sponsor, notice: 'Sponzor byl aktualizován.'
    else
      render action: 'edit'
    end
  end

  private

  def sponsor_params
    params.require(:sponsor).permit(:name, :web, :logo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    'Ty a Já'
  end

  def page_description
    'Občaské sdružeí Ty a Já'
  end

  def format_date(date)
    return '' unless date

    date.strftime('%-d.%-m.%Y')
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def types_options
    { '' => nil }.merge(Event::TYPE_TITLES.invert)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/events/_form.html.haml
- if @event.errors.any?
  .errors
    Akce nemohla být uložena, prosím zadejte údaje znovu.
    %ul
    - @event.errors.full_messages.each do |msg|
      %li= msg

= form_with(model: @event, local: true) do |form|
  .form-group
    = form.label :Název
    = form.text_field :title, class: 'form-control', required: true
  .form-group
    = form.label :Datum
    = form.text_field :date, { id: 'datepicker', class: 'form-control' }
  .form-group
    = form.label :Typ
    = select('event', 'type', types_options, class: 'form-control')
  .form-group
    = form.label :Popis
    = form.text_area :description, class: 'form-control', rows: 5, cols: 50
  .form-group
    = form.submit 'Uložit', class: 'btn btn-primary'

app/views/events/edit.html.haml
%h2 Editace akce
= render 'form'

app/views/events/index.html.haml
%h1 Události

- @events.each do |event|
  %ul
    %li
      %h3
        = link_to event.title, event_path(event)
      %strong Datum:
      = format_date(event.date)
      %p
        %strong Typ: 
        = event.event_type_title
    %p
    %li
      = event.description.html_safe
    %li
      - if user_signed_in?
        #edit
          = link_to 'Edit', edit_event_path(event)

app/views/events/new.html.haml
%h2 Nová akce
= render 'form'

app/views/events/show.html.haml
%ul
  %li
    %h3
      = @event.title
    %strong Datum:
    = format_date(@event.date)
    <br>
    %strong Typ:
    = @event.event_type_title
  %li
    = @event.description.html_safe
  %li
    #edit
      - if user_signed_in?
        =link_to 'Edit', edit_event_path(@event)

app/views/home/index.html.haml
%h1 Aktuality
%p
- @posts.each do |post|
  %ul
    %li
      %h3
        = link_to post.title, post_path(post)
    %li
      = post.text.html_safe
    %li
      - if user_signed_in?
        #edit
          = link_to 'Edit', edit_post_path(post)

app/views/layouts/application.html.haml
%html{ class: page_class }
  %head

    %link{:href => "https://fonts.googleapis.com/css?family=Francois+One|Source+Sans+Pro", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/

    = favicon_link_tag 'logo-tyaja.png'

    %meta{ charset: "utf-8" }

    %title= page_title

    %meta{ name: "description", content: page_description }

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')
    = javascript_include_tag('application', 'data-turbolinks-track': 'true')
  %body
    .page-wrap
      .outer-header
        .container
          .header
            .col
              = link_to(image_tag("banner-ty-a-ja.png", alt: "banner", height: "160"), home_index_path)
        .topnav
          .row
          %li
            = link_to('Domovská stránka', home_index_path)
          %li
            = link_to('O nás', sites_o_nas_path)
          %li
            = link_to('Podporují nás', sponsors_path)
          %li
            = link_to('Jak přispět', sites_jak_prispet_path)
          %li
            = link_to('Kontakty', sites_kontakty_path)
      .container.main
        .row
          .column.side
            %ul
              .login
                - if user_signed_in?
                  Logged in as
                  %strong= current_user.email
                  %br
                  = link_to 'Editovat profil', edit_user_registration_path
                  |
                  \#{link_to "Logout", destroy_user_session_path, method: :delete}
                - else
                  = link_to "Sign up", new_user_registration_path
                  |
                  \#{link_to "Login", new_user_session_path}
            - if user_signed_in?
              %ul
                %li
                  = link_to('Vytvořit událost', new_event_path)
                %li
                  = link_to('Vytvořit článek', new_post_path)
                %li
                  = link_to('Přidat sponzora', new_sponsor_path)
            %ul
              %li
                = link_to('Domovská stránka', home_index_path)
              %li
                = link_to('Plánované akce', events_path(type: :planned))
              %li
                = link_to('Kroužky', events_path(type: :hobby_group))
              %li
                = link_to('Kurzy', events_path(type: :course))
              %li
                = link_to('Festival na konci léta', events_path(type: :festival))
              %li
                = link_to('Fotogalerie')
          .column.middle
            = yield
    .footer
      .footer-column
        &nbsp;
      .footer-column
        %a.fa.fa-facebook-square#facebook{:href => "https://www.facebook.com/pages/biz/non_profit-plzen/Sdru%C5%BEen%C3%AD-Ty-a-J%C3%A1-zs-130135556726/"}
        %a.fa.fa-envelope-square#envelope{href: "mailto:sdruzenityaja@seznam.cz"}
      .footer-column
        .copyright
          &#169; 2018 Eva Kadlecová a Jarka Košanová.

app/views/photos/_form.html.haml
- if @photo.errors.any?
  .errors
    Fotka nemohla být uložena, prosím přidejte fotku znovu.
    %p
    - @photo .errors.full_messages.each do |msg|
      %li= msg

= form_with(model: @photo, local: true) do |form|
  .form-group
    = form.label :Název
    = form.text_field :name, class: 'form-control', required: true
  .form-group
    = form.label :Fotka
    = form.file_field :image, class: 'form-control', required: true
  .form-group
    = form.label :Popis
    = form.text_area :description, class: 'form-control', rows: 5, cols: 50
  .form-group
    = form.submit 'Uložit', class: 'btn btn-primary'

app/views/photos/new.html.haml
%h2 Nová fotka
= render 'form'

app/views/photos/show.html.haml
%ul
  = notice
  %li
    %h3
      = @photo.name
  %li
  = image_tag(@photo.image_url.to_s)
  %li
    = @photo.description
  %li
    - if user_signed_in?
      #edit
        = link_to "Smazat", photo_path(@photo), method: :delete,
        data: { confirm: 'Skutečně smazat fotku?' }

app/views/posts/_form.html.haml
- if @post.errors.any?
  .errors
    Článek nemohl být uložen, prosím zadejte údaje znovu.
    %ul
    - @post.errors.full_messages.each do |msg|
      %li= msg

= form_with(model: @post, local: true) do |form|
  .form-group
    = form.label :Název
    = form.text_field :title, class: 'form-control', required: true
  .form-group
    = form.label :Popis
    = form.text_area :text, class: 'form-control', rows: 5, cols: 50, required: true
  .form-group
    = form.submit 'Uložit', class: 'btn btn-primary'

app/views/posts/edit.html.haml
%h2 Editace článku
= render 'form'

app/views/posts/index.html.haml
%h1 Všechny články
%table
  %tr
    .bold
      %th Název
      %th Text
      %th
  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.text

app/views/posts/new.html.haml
%h2 Nový článek
= render 'form'

app/views/posts/show.html.haml
%ul
  %h3
    = @post.title
  %li
    = @post.text.html_safe
  %li
    #edit
      %strong Autor:
      = @post.user.email
      - if user_signed_in?
        |
        \#{link_to 'Edit', edit_post_path(@post)}

app/views/sites/jak_prispet.html.haml
%ul
  %h1 Jak přispět
  %li
    Naše občanské sdružení je nezisková organizace závislá na finančních darech a dotacích. Budeme
    velice potěšeni, když pomůžete naši činnost dále rozšiřovat a zkvalitňovat, tím že nám přispějete
    jakoukoliv finanční částkou či věcným darem.
  %li
    Velice uvítáme vaši pomoc při akcích, které pořádáme (festival Na konci léta, koncerty,
    ples sdružení…), ať už vaší účastí jako divák či jako dobrovolník, který nám pomůže s organizací.
  %li
    Chcete-li zlepšit kvalitu námi nabízených služeb, či přispět na vybavení nových prostorů v
    Resslově ulici, můžete zaslat libovolnou částku na konto sbírky pro Ty a Já,
    které má číslo 198380634/0300.
  %li
    Přispět nám můžete také zakoupením našich výrobků z keramické dílny a výrobků vyrobených na
    kroužcích v o. s. Ty a Já, nebo koupí CD Hudební laboratoře za symbolickou cenu 100 Kč.
  %li
    <b><font size="4" style="font-family:Francois One;">Číslo účtu: 198380634/0300 ČSOB, a.s.</font></b>
  %li
    Velice uvítáme vaši pomoc při akcích, které pořádáme (festival Na konci léta, koncerty,
    ples sdružení…), ať už vaší účastí jako divák či jako dobrovolník, který nám pomůže s organizací.
  %li
    %img
      = link_to(image_tag("jak-prispet.jpg", alt: "jak_prispet"), sites_jak_prispet_path)

app/views/sites/kontakty.html.haml
%ul
  %h1 Kontakty
  %p
  .container_contacts
    .column_contacts
      %h3 Výbor spolku:<br>
      Jitka Malafová (předsedkyně) <br>
      Martina Šnajdrová<br>
      Mgr. Jitka Vachulková<br>
      %li
        %p
          %h3 Adresa:<br>
          Sdružení Ty a Já, z. s.<br>
          Resslova 14<br>
          301 00 Plzeň<br>
      %li
        %p
          IČ: 27007278<br>
    .column_contacts
      %h3 Kontakty:<br>
      Telefon: 776 488 008<br>
      #web_link
        Email:
        %a{href: "mailto:sdruzenityaja@seznam.cz"} sdruzenityaja@seznam.cz<br>
        %p
      %li
        %a.fa.fa-facebook-square#facebook-icon{:href => "https://www.facebook.com/pages/biz/non_profit-plzen/Sdru%C5%BEen%C3%AD-Ty-a-J%C3%A1-zs-130135556726/"}
  .map
    %iframe{allowfullscreen: "", frameborder: "0", height: "400", src: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5156.669921197158!2d13.372917833523651!3d49.742140940873675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470af1e37319f25b%3A0xfe5a804584ae995e!2zUmVzc2xvdmEgMzcwLzE0LCAzMDEgMDAgUGx6ZcWIIDMtSmnFvm7DrSBQxZllZG3Em3N0w60!5e0!3m2!1scs!2scz!4v1534495214104", style: "border:0", width: "400"}

app/views/sites/o_nas.html.haml
%ul
  %h1 O Nás
  %li
    Sdružení Ty a Já bylo založeno v září roku 2005 z iniciativy rodičů handicapovaných dětí.
    Pomáhá nejen handicapovaným mladým lidem se začleněním se do společnosti. Nabízí smysluplné
    trávení volného času všem mladým lidem.
  %li
    Zajišťujeme a pořádáme kulturní, společenské a sportovní akce a to nejen v Plzni.
    Vzniká zde hodně zajímavých věcí, které by za normálních podmínek jen těžko přišly na svět.
  %li
    Video o sdružení Ty a Já
    %a.fa.fa-youtube-square#youtube{:href => "https://www.youtube.com/watch?v=92jmcsiD4iw"}
  %li
    %img
      = link_to(image_tag("o_nas.png", alt: "o_nas"), sites_o_nas_path)

app/views/sponsors/_form.html.haml
- if @sponsor.errors.any?
  .errors
    Sponzor nemohl být uložen, prosím zadejte údaje znovu.
    %ul
    - @sponsor.errors.full_messages.each do |msg|
      %li= msg

= form_with(model: @sponsor, local: true) do |form|
  .form-group
    = form.label :Jméno
    = form.text_field :name, class: 'form-control', required: true
  .form-group
    = form.label :Web
    = form.text_field :web, class: 'form-control', type: 'url'
  .form-group
    = form.label :Logo
    = form.file_field :logo, class: 'form-control'
  .form-group
    = form.submit 'Uložit', class: 'btn btn-primary'

app/views/sponsors/edit.html.haml
%h2 Editace sponzora
= render 'form'

app/views/sponsors/index.html.haml
%h1 Podporují nás
- @sponsors.each do |sponsor|
  %ul
    %p
      %img2
        = image_tag(sponsor.logo_url(:thumb).to_s)
      %h3
        = link_to sponsor.name, sponsor_path(sponsor)
      #web_link
        = link_to sponsor.web, sponsor.web
      - if user_signed_in?
        #edit
          %td= link_to 'Edit', edit_sponsor_path(sponsor)

app/views/sponsors/new.html.haml
%h2 Nový sponzor
= render 'form'

app/views/sponsors/show.html.haml
%ul
  = notice
  %li
    %h3
      = @sponsor.name
  %li
    %strong Web:
    = @sponsor.web
  %li
    %img
      = image_tag(@sponsor.logo_url.to_s)

app/views/users/index.html.haml
%h1 Seznam uživatelů
%table
  %tr
    .bold
      %th Email
      %th Heslo
      %th
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.encrypted_password